config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "static_pages#home"

  resources :residents
  resources :rooms

  # Clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resident.rb
# frozen_string_literal: true

class Resident < ApplicationRecord
  belongs_to :room
  validates :name, length: { in: 1..150 }
  validates :bio, length: { in: 10..10000 }
  validate :dob_not_in_future

  private
    def dob_not_in_future
      if dob >= Date.today
        errors.add :dob, "must be in the past"
      end
    end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :residents, dependent: :restrict_with_exception
  validates :name, length: { in: 1..50 }

  def self.alphabetical
    Room.all.order(:name)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/residents_controller.rb
# frozen_string_literal: true

class ResidentsController < ApplicationController
  before_action :require_login
  before_action :set_resident, only: [:show, :edit, :update, :destroy]

  # GET /residents
  # GET /residents.json
  def index
    @residents = Resident.all
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
  end

  # GET /residents/new
  def new
    @resident = Resident.new
  end

  # GET /residents/1/edit
  def edit
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = Resident.new(resident_params)

    respond_to do |format|
      if @resident.save
        format.html { redirect_to @resident, notice: "Resident was successfully created." }
        format.json { render :show, status: :created, location: @resident }
      else
        format.html { render :new }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residents/1
  # PATCH/PUT /residents/1.json
  def update
    respond_to do |format|
      if @resident.update(resident_params)
        format.html { redirect_to @resident, notice: "Resident was successfully updated." }
        format.json { render :show, status: :ok, location: @resident }
      else
        format.html { render :edit }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident.destroy
    respond_to do |format|
      format.html { redirect_to residents_url, notice: "Resident was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resident
      @resident = Resident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resident_params
      params.require(:resident).permit(:name, :dob, :room_id, :bio)
    end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :require_login
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.alphabetical
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Clearance::SessionsController
  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        redirect_back_or url_after_create
      else
        flash.now.notice = status.failure_message
        render component: "SignInPage", tag: "main", class: "content-pane"
        # render template: "sessions/new", status: :unauthorized
      end
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    # flash[:error] = "Demo error"
    render component: "HomePage", tag: "main", class: "content-pane"
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = "")
    base_title = "carehomely"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_flash.html.erb
<% if flash.keys.length > 0 %>
  <div class="flashes">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_toolbar.html.erb
<nav class="toolbar">
  <nav class="subtoolbar">
    <% if signed_in? %>
      <%= link_to 'Rooms', rooms_path, class: 'button' %>
      <%= link_to 'Residents', residents_path, class: 'button' %>
    <% end %>
  </nav>
  <nav class="subtoolbar">
    <%= link_to 'carehomely', root_path, class: 'logo' %>
  </nav>
  <nav class="subtoolbar">
    <% if signed_in? %>
      <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'button' %>
    <% else %>
      <%= link_to 'Admin sign in', sign_in_path, class: 'button' %>
      <%= link_to 'Create admin user', sign_up_path, class: 'button' %>
    <% end %>
  </nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/toolbar' %>
    <%= render 'layouts/flash' %>
    <main class="page">
      <%= yield %>
    </main>
  </body>
</html>

app/views/residents/_form.html.erb
<%= form_with(model: resident, local: true) do |form| %>
  <% if resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resident.errors.count, "error") %> stopped this resident from being saved:</h2>

      <ul>
      <% resident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob, start_year: 100.years.ago.year, end_year: 1.year.ago.year %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.collection_select :room_id, Room.alphabetical, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button small' %>
    <%= link_to "Cancel", resident, class: "button small" %>
  </div>
<% end %>

app/views/residents/_resident_card.html.erb
<div class="resident-card">
  <div class="info-area">
    <h3 class="name"><%= link_to resident.name, resident %></h3>
    <p>Born: <%= resident.dob %></p>
    <% if resident.room %>
      <p>Residing in: <%= link_to resident.room.name, resident.room, class: "button small" %></p>
    <% elsif %>
      <p>Not currently allocated to a room</p>
    <% end %>
  </div>
  <%= image_tag "https://www.thinkrevivehealth.com/sites/default/files/styles/thumbnail/public/default_images/portrait-placeholder.png?itok=IhJi0rSm", class: "image" %>
  <%= link_to 'Edit', edit_resident_path(resident), class: "edit" %>
  <%= link_to 'Delete', resident, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %>
</div>

app/views/residents/edit.html.erb
<% provide(:title, "Edit #{@resident.name} | Residents") %>
<h1>Editing resident details: <%= @resident.name %></h1>
<%= render 'form', resident: @resident %>

app/views/residents/index.html.erb
<% provide(:title, "Residents") %>
<div class="residents">
  <h1>Residents</h1>

  <%= link_to 'Register a new resident', new_resident_path, class: 'button' %>

  <div class="residents-list">
    <% @residents.each_with_index do |resident, i| %>
      <%= render 'resident_card', resident: resident, index: i %>
    <% end %>
  </div>
</div>

app/views/residents/new.html.erb
<% provide(:title, "Add a new resident") %>
<h1>New Resident</h1>

<%= render 'form', resident: @resident %>

app/views/residents/show.html.erb
<% provide(:title, "#{@resident.name} | Residents") %>
<div class="resident">
  <%= render 'resident_card', resident: @resident, index: 0 %>
  <h2>Bio</h2>
  <p><%= @resident.bio %></p>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> stopped this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Register room", class: "button small" %>
    <%= link_to "Cancel", room, class: "button small" %>
  </div>
<% end %>

app/views/rooms/_room_card.html.erb
<div class="room-card <%= 'cannot-delete' if room.residents.length > 0 %>">
  <div class="info-area">
    <h3 class="name"><%= link_to room.name, room %></h3>
    <% if room.residents.length > 0 %>
      <p>
      <% room.residents.each do |resident| %>
        <%= link_to resident.name, resident, class: "button small" %>
      <% end %>
      </p>
    <% elsif %>
      <p>Not currently allocated any residents</p>
    <% end %>
  </div>
  <%= image_tag "room_#{(index % 2) + 1}.jpg", class: "image" %>
  <%= link_to 'Edit', edit_room_path(room), class: "edit" %>
  <% if room.residents.length == 0 %>
    <%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<% provide(:title, "Edit #{@room.name} | Rooms") %>
<h1>Editing room details: <%= @room.name %></h1>
<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<% provide(:title, "Rooms") %>
<div class="rooms">
  <h1>Rooms</h1>

  <%= link_to 'Register a new room', new_room_path, class: 'button' %>

  <div class="room-list">
    <% @rooms.each_with_index do |room, i| %>
      <%= render 'room_card', room: room, index: i %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<% provide(:title, "Register a new room") %>
<h1><%= yield(:title) %></h1>
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<% provide(:title, "#{@room.name} | Rooms") %>
<div class="room">
  <%= render 'room_card', room: @room, index: 0 %>

  <% if @room.residents.length > 0 %>
  <h2>Current residents</h2>
  <div class="residents-list">
    <% @room.residents.each_with_index do |resident, i| %>
      <%= render 'residents/resident_card', resident: resident, index: i %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<p>
Welcome to <span class="emphasise">carehomely</span>, a demo application created
by Jack Preston.
</p>

<p>
To use the app, you'll need to
<%= link_to "log in", sign_in_path, class: "true-link" %>
as an admin user. Don't worry, though: the
<%= link_to "registration page", sign_up_path, class: "true-link" %>
will accept any credentials you give it. This is just a demo, after all!
</p>

<p>
You can find the source code on <%= link_to "Github", "https://github.com/unwitting/chomely", class: "true-link" %>.
I've left some notes on some choices I made and what I would like to do with a bit more time
in <%= link_to "README.md", "https://github.com/unwitting/chomely/blob/master/README.md", class: "true-link" %>.
</p>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Register a new admin user") %>
<div id="clearance" class="sign-up">
  <h2><%= yield(:title) %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit(class: 'button small') %>
    </div>
  <% end %>
</div>